name: Deploy Frontend (S3 + CloudFront)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
          
      - name: Build and Export Next.js
        run: |
          npm run build
          npx next export

      - name: Build Check
        run: |
          ls -la
          ls -la out || echo "out directory not found"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Sync to S3
        run: |
          # out 디렉토리가 존재하는지 확인
          if [ -d "./out" ]; then
            aws s3 sync ./out/ s3://${{ secrets.S3_BUCKET }} --delete
          else
            echo "Error: out directory not found"
            ls -la
            exit 1
          fi

      - name: Invalidate CloudFront Cache
        if: success()
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.DISTRIBUTION_ID }} \
            --paths "/*"
